### ISSUE TITLE
Please support special designator prefix `@FD:N`

### ISSUE THREAD

**Issue by vanitasvitae** [pgpainless/sop-java#12]
Originally posted by @dkg in https://github.com/pgpainless/pgpainless/issues/329
> Supporting a special designator prefix @FD:NNN (where NNN is an ASCII representation of an integer written in decimal) makes it possible for tooling to use pgpainless-cli without writing to the filesystem.
>
>https://stackoverflow.com/questions/4845122/using-a-numbered-file-descriptor-from-java suggests that native Java can't do this directly, >but on systems that support /dev/fd/NNN this can be worked around by just opening the corresponding path when present.
>
>Perhaps pgpainless-cli could do that to support the file descriptor special designator on systems that support /dev/fd/NNN explicitly?

**Comment by vanitasvitae** [comment]
I did some initial experimenting with file descriptors when I first implemented the SOP API. However, I did not really fully understood it back then. In the end I decided to not support them until there was a real-world use-case, like at least one user that might find them useful.

I will do some more digging to figure out how to implement this in a sane way :)

**Comment by dkg** [comment]
here's [a real-world use case](https://gitlab.com/hagrid-keyserver/bootstrap-committee/-/merge_requests/15)

**Comment by vanitasvitae** [comment]
I added support for file descriptors via https://github.com/pgpainless/sop-java/commit/87d561966fe9ce6499a44da364271e0d65d4e2b1

Does the implementation look sane to you?
I check, whether the directory `/dev/fd/` exists. If it doesn't I throw a `UNSUPPORTED_SPECIAL_PREFIX` error.
Next I check, if the part behind `@FD:` is a 1-3 digit number.
Lastly, I try to open either a `FileInputStream` or `FileOutputStream` on `/dev/fd/NNN` where `NNN` is the number I validated in the previous step.
It may happen that the user tries to open a stream on a file descriptor that doesn't exist. In this case I throw an IOException explaining that the file descriptor was not found.

I never worked with FDs before, so I'm unsure. However, my initial testing appears to confirm that it works as intended, e.g.
`pgpainless-cli inline-verify --verifications-out @FD:1 key.asc` prints the verifications to stdout, just below the message.
Generating keys with passwords from a FD also works as intended.

**Comment by dkg** [comment]
Thanks for this work!  i don't think i know java well enough to be able to give you a proper code review, but i can review your textual summary: that part sounds good except for the limitation of only looking for a 1-3 digit number.  on my debian system, which runs a fairly stock kernel, the number of open file descriptor could be much much more than 99:

```
0 dkg@alice:~$ cat /proc/sys/fs/file-max 
9223372036854775807
0 dkg@alice:~$ 
```

otherwise, it all sounds reasonable to me.
