### ISSUE TITLE
`decrypt --with-session-key` is very finicky about the format

### ISSUE THREAD

**Issue by dkg** [pgpainless/sop-java#14]
If a `SESSIONKEY` file has a trailing newline, or has hex digits in lowercase, `pgpainless-cli` complains:

> Session keys are expected in the format 'ALGONUM:HEXKEY'.

It would be better to accept trailing newlines, and lowercase hex as well.

**Comment by vanitasvitae** [comment]
Good idea!

**Comment by vanitasvitae** [comment]
Fixed in aa953428ee7c3cb8ebbbe251141352c7632aa53e
