### ISSUE TITLE
Uses cleartextsigned instead of clearsigned for --as argument

### ISSUE THREAD

**Issue by guillemj** [pgpainless/sop-java#16]
The latest SOP draft specifies "clearsigned" as the valid value instead of "cleartextsigned". This is currently affecting the upcoming dpkg OpenPGP multi-backend support that includes SOP and pgpainless-cli as one of its alternatives.

**Comment by vanitasvitae** [comment]
Hm, I wonder how that bug ended up in the implementation :D
Fixing this will be easy though. Thanks for the report!
