### ISSUE TITLE
picocli treats passwords and session-key input as direct parameters (strings) rather than indirect (file references)

### ISSUE THREAD

**Issue by dkg** [pgpainless/sop-java#2]
The spec refers to both `SESSIONKEY` and `PASSWORD` data types as *indirect* data types, not *direct* data types.

However, I notice that the picocli for sop accepts passwords and session keys directly on the command line.  For example:

```bash
printf abc123 > password.txt
echo test | sop encrypt --password password.txt
```
will use the literal string `password.txt` as the password instead of `abc123`.  

This happens for session-key input as well as passwords (i note that it does treat session-key *output* correctly, as an indirect parameter).  See discussion at https://gitlab.com/dkg/openpgp-stateless-cli/-/issues/45 about how this was never extremely clear in the spec, sorry about that!

Here are two example lines that treat the incoming parameters as strings:

https://github.com/pgpainless/sop-java/blob/a2f20693800a7e45d6f8613c09419a3c0773e9cd/sop-java-picocli/src/main/java/sop/cli/picocli/commands/EncryptCmd.java#L39

https://github.com/pgpainless/sop-java/blob/a2f20693800a7e45d6f8613c09419a3c0773e9cd/sop-java-picocli/src/main/java/sop/cli/picocli/commands/DecryptCmd.java#L52

**Comment by vanitasvitae** [comment]
I think what particularly contributes to this misunderstanding is the following wording:

```
sop encrypt [--as={binary|text|mime}]
       [--no-armor]
       [--with-password=PASSWORD...]    <-- PASSWORD
       [--sign-with=KEYS...]
       [--] [CERTS...]

...

--with-password enables symmetric encryption (and can be used
   multiple times if multiple passwords are desired).  If sop encrypt
   encounters a PASSWORD which is not a valid UTF-8 string        <-- PASSWORD
   ([Section 8.7](https://datatracker.ietf.org/doc/html/draft-dkg-openpgp-stateless-cli-03#section-8.7)), or is otherwise not robust in its representation to
   humans, it fails with PASSWORD_NOT_HUMAN_READABLE.  If sop encrypt
   sees trailing whitespace at the end of a PASSWORD, it will trim the
   trailing whitespace before using the password.  See [Section 8.8](https://datatracker.ietf.org/doc/html/draft-dkg-openpgp-stateless-cli-03#section-8.8) for
   more discussion about passwords.
```

In the argument list the filename is called PASSWORD. Later in the text, the content of the PASSWORD file is being addressed with the name PASSWORD. This suggests that PASSWORD is a string, not a file.
